// Mulkchi.Frontend/src/app/features/auth/register/register.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { RegisterRequest } from '../../../core/models/auth.model';
import { AuthService } from '../../../core/services/auth.service';
import { LoggingService } from '../../../core/services/logging.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, TranslateModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss'],
})
export class RegisterComponent {
  firstName = '';
  lastName = '';
  email = '';
  phone = '';
  password = '';
  confirmPassword = '';
  acceptTerms = false;
  showPassword = false;
  showConfirmPassword = false;
  loading = false;
  errorMsg = '';

  private authService = inject(AuthService);
  private router = inject(Router);
  private logger = inject(LoggingService);

  register() {
    if (!this.firstName || !this.email || !this.password || !this.phone) {
      this.errorMsg = "Barcha maydonlarni to'ldiring";
      return;
    }

    if (this.password.length < 6) {
      this.errorMsg = "Parol kamida 6 ta belgidan iborat bo'lishi kerak";
      return;
    }

    if (this.password !== this.confirmPassword) {
      this.errorMsg = 'Parollar mos kelmadi';
      return;
    }

    if (!this.acceptTerms) {
      this.errorMsg = 'Foydalanish shartlariga rozilik bildiring';
      return;
    }

    const registerRequest: RegisterRequest = {
      firstName: this.firstName,
      lastName: this.lastName,
      email: this.email,
      phone: this.phone,
      password: this.password,
      preferredLanguage: 'uz',
    };

    this.loading = true;
    this.errorMsg = '';

    this.authService.register(registerRequest).subscribe({
      next: (response) => {
        this.loading = false;
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.loading = false;

        if (err.status === 409) {
          this.errorMsg =
            "Bu email allaqachon ro'yxatdan o'tgan. Iltimos, boshqa emaildan foydalaning.";
        } else if (err.status === 400) {
          this.errorMsg = "Ma'lumotlar noto'g'ri. Iltimos, barcha maydonlarni to'g'ri to'ldiring.";
        } else {
          this.errorMsg = "Ro'yxatdan o'tishda xatolik. Iltimos, qayta urinib ko'ring.";
        }
        this.logger.error('Registration error:', err);
      },
    });
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }
}

<div class="min-h-screen bg-gray-50 flex flex-col">
  <header class="py-4 px-4 border-b border-gray-200 bg-white">
    <div class="max-w-7xl mx-auto">
      <a routerLink="/" class="flex items-center gap-2 w-fit">
        <div class="flex h-9 w-9 items-center justify-center rounded-lg bg-brand text-white font-bold text-xl">M</div>
        <span class="text-xl font-bold text-dark">Mulkchi</span>
      </a>
    </div>
  </header>

  <main class="flex-1 flex items-center justify-center p-4 sm:p-6">
    <div
      class="w-full max-w-6xl flex flex-col md:flex-row bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden">
      <div
        class="hidden md:flex flex-col justify-center items-start w-1/2 bg-brand text-white p-12 lg:p-20 relative overflow-hidden">
        <div
          class="absolute inset-0 opacity-10 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-white to-transparent">
        </div>

        <div class="relative z-10">
          <div class="flex items-center gap-3 mb-10">
            <div class="bg-white text-brand p-2 rounded-xl shadow-md">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
                <path
                  d="M11.47 3.84a.75.75 0 011.06 0l8.99 8.99a.75.75 0 11-1.06 1.06l-1.46-1.46V20.25a1.5 1.5 0 01-1.5 1.5H6.5a1.5 1.5 0 01-1.5-1.5V12.43L3.53 13.9a.75.75 0 11-1.06-1.06l8.99-8.99z" />
              </svg>
            </div>
            <span class="text-3xl font-extrabold tracking-tight">Mulkchi</span>
          </div>

          <h2 class="text-4xl lg:text-5xl font-bold mb-8 leading-tight">
            Yangi akkaunt<br>yaratish
          </h2>

          <div class="space-y-4 text-lg">
            <div class="flex items-center gap-3">
              <svg class="w-6 h-6 text-green-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              Bir daqiqada bepul ro'yxatdan o'ting
            </div>
            <div class="flex items-center gap-3">
              <svg class="w-6 h-6 text-green-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              Mulk izlang yoki e'lon bering
            </div>
            <div class="flex items-center gap-3">
              <svg class="w-6 h-6 text-green-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              Xavfsiz va ishonchli to'lovlar
            </div>
            <div class="flex items-center gap-3">
              <svg class="w-6 h-6 text-green-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              24/7 mijozlar qo'llab-quvvatlashi
            </div>
          </div>
        </div>
      </div>

      <div class="w-full md:w-1/2 flex items-center justify-center p-6 sm:p-10">
        <div class="w-full max-w-md p-2 sm:p-4 animate-fade-in">
          <div class="text-center mb-8">
            <h1 class="text-3xl font-bold text-dark mb-2">Ro'yxatdan o'tish</h1>
            <p class="text-light">Mulkchi tizimida o'z akkauntingizni yarating</p>
          </div>

          @if (errorMsg) {
          <div
            class="bg-red-50 text-red-600 border border-red-200 p-4 rounded-xl mb-6 flex items-center gap-3 text-sm font-medium animate-fade-in">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 flex-shrink-0" viewBox="0 0 20 20"
              fill="currentColor">
              <path fill-rule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z"
                clip-rule="evenodd" />
            </svg>
            <span>{{ errorMsg }}</span>
          </div>
          }

          <form class="space-y-5" (submit)="$event.preventDefault(); register()">

            <div class="grid grid-cols-2 gap-4">
              <div class="flex flex-col">
                <label class="text-sm font-medium text-dark mb-1 ml-1">Ism</label>
                <input type="text" [(ngModel)]="firstName" name="firstName" placeholder="Ali"
                  class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-dark focus:ring-2 focus:ring-brand focus:border-brand outline-none transition">
              </div>
              <div class="flex flex-col">
                <label class="text-sm font-medium text-dark mb-1 ml-1">Familiya</label>
                <input type="text" [(ngModel)]="lastName" name="lastName" placeholder="Valiyev"
                  class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-dark focus:ring-2 focus:ring-brand focus:border-brand outline-none transition">
              </div>
            </div>

            <div class="flex flex-col">
              <label class="text-sm font-medium text-dark mb-1 ml-1">Email</label>
              <input type="email" [(ngModel)]="email" name="email" placeholder="email@misol.com"
                class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-dark focus:ring-2 focus:ring-brand focus:border-brand outline-none transition">
            </div>

            <div class="flex flex-col">
              <label class="text-sm font-medium text-dark mb-1 ml-1">Telefon raqam</label>
              <input type="tel" [(ngModel)]="phone" name="phone" placeholder="+998 90 123 45 67"
                class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-dark focus:ring-2 focus:ring-brand focus:border-brand outline-none transition" />
            </div>

            <div class="flex flex-col">
              <label class="text-sm font-medium text-dark mb-1 ml-1">Parol</label>
              <div class="relative">
                <input [type]="showPassword ? 'text' : 'password'" [(ngModel)]="password" name="password"
                  placeholder="Kamida 6 ta belgi"
                  class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 pr-12 py-3 text-dark focus:ring-2 focus:ring-brand focus:border-brand outline-none transition" />
                <button type="button" (click)="togglePasswordVisibility()"
                  class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-dark"
                  aria-label="Toggle password visibility">
                  @if (showPassword) {
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                    stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round"
                      d="M3 3l18 18M10.477 10.48A3 3 0 0013.52 13.52M9.88 5.09A10.93 10.93 0 0112 4.875c4.5 0 8.258 2.943 9.542 6.995a11.052 11.052 0 01-2.104 3.292M6.228 6.228A10.944 10.944 0 002.458 11.87a11.052 11.052 0 005.243 6.128A10.92 10.92 0 0012 19.125c1.733 0 3.373-.402 4.83-1.117" />
                  </svg>
                  } @else {
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                    stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round"
                      d="M2.458 12C3.732 7.943 7.523 5.063 12 5.063c4.477 0 8.268 2.88 9.542 6.937-1.274 4.057-5.065 6.938-9.542 6.938-4.477 0-8.268-2.88-9.542-6.938z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                  }
                </button>
              </div>
            </div>

            <div class="flex flex-col">
              <label class="text-sm font-medium text-dark mb-1 ml-1">Parolni tasdiqlang</label>
              <div class="relative">
                <input [type]="showConfirmPassword ? 'text' : 'password'" [(ngModel)]="confirmPassword"
                  name="confirmPassword" placeholder="Parolni qayta kiriting"
                  class="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 pr-12 py-3 text-dark focus:ring-2 focus:ring-brand focus:border-brand outline-none transition" />
                <button type="button" (click)="toggleConfirmPasswordVisibility()"
                  class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-dark"
                  aria-label="Toggle confirm password visibility">
                  @if (showConfirmPassword) {
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                    stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round"
                      d="M3 3l18 18M10.477 10.48A3 3 0 0013.52 13.52M9.88 5.09A10.93 10.93 0 0112 4.875c4.5 0 8.258 2.943 9.542 6.995a11.052 11.052 0 01-2.104 3.292M6.228 6.228A10.944 10.944 0 002.458 11.87a11.052 11.052 0 005.243 6.128A10.92 10.92 0 0012 19.125c1.733 0 3.373-.402 4.83-1.117" />
                  </svg>
                  } @else {
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                    stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round"
                      d="M2.458 12C3.732 7.943 7.523 5.063 12 5.063c4.477 0 8.268 2.88 9.542 6.937-1.274 4.057-5.065 6.938-9.542 6.938-4.477 0-8.268-2.88-9.542-6.938z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                  }
                </button>
              </div>
            </div>

            <label class="flex items-start gap-2 text-sm text-dark select-none">
              <input type="checkbox" [(ngModel)]="acceptTerms" name="acceptTerms"
                class="mt-0.5 rounded border-gray-300 text-brand focus:ring-brand" />
              <span>
                <a href="#" class="text-brand hover:underline">Foydalanish shartlari</a>
                va
                <a href="#" class="text-brand hover:underline">maxfiylik siyosati</a>
                ga roziman
              </span>
            </label>

            <div class="relative my-2">
              <div class="absolute inset-0 flex items-center">
                <div class="w-full border-t border-gray-200"></div>
              </div>
              <div class="relative flex justify-center text-xs uppercase">
                <span class="bg-white px-2 text-gray-400">yoki</span>
              </div>
            </div>

            <div class="grid grid-cols-2 gap-3">
              <button type="button"
                class="w-full rounded-xl border border-gray-200 py-2.5 text-sm font-medium hover:bg-gray-50 transition">Google</button>
              <button type="button"
                class="w-full rounded-xl border border-gray-200 py-2.5 text-sm font-medium hover:bg-gray-50 transition">Facebook</button>
            </div>

            <button type="submit" [disabled]="loading"
              class="w-full bg-brand text-white font-bold rounded-xl px-4 py-3.5 shadow-md hover:bg-brand/90 transition disabled:opacity-70 flex justify-center items-center gap-2">
              @if (loading) {
              <svg class="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z">
                </path>
              </svg>
              <span>Ro'yxatdan o'tilmoqda...</span>
              } @else {
              <span>Ro'yxatdan o'tish</span>
              }
            </button>
          </form>

          <div class="mt-8 text-center text-sm text-light">
            Allaqachon hisobingiz bormi?
            <a routerLink="/login" class="font-bold text-brand hover:underline">Tizimga kirish</a>
          </div>
        </div>
      </div>

    </div>
  </main>

  <footer class="py-4 px-4 text-center text-sm text-light border-t border-gray-200 bg-white">
    © 2026 Mulkchi. Barcha huquqlar himoyalangan.
  </footer>
</div>

// _v0_import/app/auth/register/page.tsx
"use client"

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Eye, EyeOff, Phone, Lock, User, AlertCircle, Loader2, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import { cn } from '@/lib/utils'

interface FormErrors {
  name?: string
  phone?: string
  password?: string
  confirmPassword?: string
  terms?: string
  general?: string
}

export default function RegisterPage() {
  const router = useRouter()
  const [isLoading, setIsLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    password: '',
    confirmPassword: '',
    terms: false
  })
  const [errors, setErrors] = useState<FormErrors>({})

  const passwordStrength = (password: string): { score: number; label: string; color: string } => {
    let score = 0
    if (password.length >= 6) score++
    if (password.length >= 8) score++
    if (/[A-Z]/.test(password)) score++
    if (/[0-9]/.test(password)) score++
    if (/[^A-Za-z0-9]/.test(password)) score++

    if (score <= 1) return { score, label: 'Juda zaif', color: 'bg-destructive' }
    if (score === 2) return { score, label: 'Zaif', color: 'bg-gold' }
    if (score === 3) return { score, label: "O'rtacha", color: 'bg-gold' }
    if (score === 4) return { score, label: 'Kuchli', color: 'bg-green' }
    return { score, label: 'Juda kuchli', color: 'bg-green' }
  }

  const validateForm = (): boolean => {
    const newErrors: FormErrors = {}

    if (!formData.name.trim()) {
      newErrors.name = 'Ismingizni kiriting'
    } else if (formData.name.trim().length < 2) {
      newErrors.name = 'Ism kamida 2 ta harfdan iborat bo\'lishi kerak'
    }

    if (!formData.phone) {
      newErrors.phone = 'Telefon raqam kiriting'
    } else if (!/^\+998\s?\d{2}\s?\d{3}\s?\d{2}\s?\d{2}$/.test(formData.phone.replace(/\s/g, ''))) {
      newErrors.phone = 'Noto\'g\'ri format. Masalan: +998 90 123 45 67'
    }

    if (!formData.password) {
      newErrors.password = 'Parol kiriting'
    } else if (formData.password.length < 6) {
      newErrors.password = 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak'
    }

    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'Parolni tasdiqlang'
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Parollar mos kelmadi'
    }

    if (!formData.terms) {
      newErrors.terms = 'Foydalanish shartlariga rozilik bildiring'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return

    setIsLoading(true)
    setErrors({})

    // Simulate API call
    setTimeout(() => {
      setIsLoading(false)
      // On success, redirect to login
      router.push('/auth/login')
    }, 1500)
  }

  const handlePhoneChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value = e.target.value.replace(/[^\d+]/g, '')
    
    if (value.startsWith('+998')) {
      if (value.length > 4) {
        value = `+998 ${value.slice(4, 6)} ${value.slice(6, 9)} ${value.slice(9, 11)} ${value.slice(11, 13)}`
      }
    } else if (value.startsWith('998')) {
      value = `+${value}`
    } else if (value.length > 0 && !value.startsWith('+')) {
      value = `+998 ${value}`
    }
    
    setFormData(prev => ({ ...prev, phone: value.trim() }))
    if (errors.phone) setErrors(prev => ({ ...prev, phone: undefined }))
  }

  const strength = passwordStrength(formData.password)

  return (
    <div className="w-full max-w-md">
      <div className="bg-card rounded-xl p-6 sm:p-8" style={{ boxShadow: 'var(--shadow)' }}>
        {/* Header */}
        <div className="text-center mb-6">
          <h1 className="text-2xl font-bold text-foreground mb-2">Ro&apos;yxatdan o&apos;tish</h1>
          <p className="text-sm text-muted-foreground">
            Yangi hisob yaratish uchun ma&apos;lumotlaringizni kiriting
          </p>
        </div>

        {/* Error Banner */}
        {errors.general && (
          <div className="flex items-center gap-2 p-3 mb-4 rounded-lg bg-destructive/10 text-destructive text-sm">
            <AlertCircle className="h-4 w-4 shrink-0" />
            <span>{errors.general}</span>
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Name */}
          <div className="space-y-2">
            <Label htmlFor="name">Ismingiz</Label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                id="name"
                type="text"
                placeholder="Ism Familiya"
                value={formData.name}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, name: e.target.value }))
                  if (errors.name) setErrors(prev => ({ ...prev, name: undefined }))
                }}
                className={cn(
                  'pl-10',
                  errors.name && 'border-destructive focus-visible:ring-destructive'
                )}
              />
            </div>
            {errors.name && (
              <p className="text-xs text-destructive">{errors.name}</p>
            )}
          </div>

          {/* Phone */}
          <div className="space-y-2">
            <Label htmlFor="phone">Telefon raqam</Label>
            <div className="relative">
              <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                id="phone"
                type="tel"
                placeholder="+998 90 123 45 67"
                value={formData.phone}
                onChange={handlePhoneChange}
                className={cn(
                  'pl-10',
                  errors.phone && 'border-destructive focus-visible:ring-destructive'
                )}
              />
            </div>
            {errors.phone && (
              <p className="text-xs text-destructive">{errors.phone}</p>
            )}
          </div>

          {/* Password */}
          <div className="space-y-2">
            <Label htmlFor="password">Parol</Label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                id="password"
                type={showPassword ? 'text' : 'password'}
                placeholder="Kamida 6 ta belgi"
                value={formData.password}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, password: e.target.value }))
                  if (errors.password) setErrors(prev => ({ ...prev, password: undefined }))
                }}
                className={cn(
                  'pl-10 pr-10',
                  errors.password && 'border-destructive focus-visible:ring-destructive'
                )}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              >
                {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </button>
            </div>
            {/* Password Strength */}
            {formData.password && (
              <div className="space-y-1">
                <div className="flex gap-1">
                  {[...Array(5)].map((_, i) => (
                    <div
                      key={i}
                      className={cn(
                        'h-1 flex-1 rounded-full transition-colors',
                        i < strength.score ? strength.color : 'bg-secondary'
                      )}
                    />
                  ))}
                </div>
                <p className="text-xs text-muted-foreground">Kuchlilik: {strength.label}</p>
              </div>
            )}
            {errors.password && (
              <p className="text-xs text-destructive">{errors.password}</p>
            )}
          </div>

          {/* Confirm Password */}
          <div className="space-y-2">
            <Label htmlFor="confirmPassword">Parolni tasdiqlang</Label>
            <div className="relative">
              <Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                id="confirmPassword"
                type={showConfirmPassword ? 'text' : 'password'}
                placeholder="Parolni qayta kiriting"
                value={formData.confirmPassword}
                onChange={(e) => {
                  setFormData(prev => ({ ...prev, confirmPassword: e.target.value }))
                  if (errors.confirmPassword) setErrors(prev => ({ ...prev, confirmPassword: undefined }))
                }}
                className={cn(
                  'pl-10 pr-10',
                  errors.confirmPassword && 'border-destructive focus-visible:ring-destructive'
                )}
              />
              <button
                type="button"
                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              >
                {showConfirmPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </button>
              {formData.confirmPassword && formData.password === formData.confirmPassword && (
                <Check className="absolute right-10 top-1/2 h-4 w-4 -translate-y-1/2 text-green" />
              )}
            </div>
            {errors.confirmPassword && (
              <p className="text-xs text-destructive">{errors.confirmPassword}</p>
            )}
          </div>

          {/* Terms */}
          <div className="space-y-2">
            <div className="flex items-start gap-2">
              <Checkbox
                id="terms"
                checked={formData.terms}
                onCheckedChange={(checked) => {
                  setFormData(prev => ({ ...prev, terms: checked as boolean }))
                  if (errors.terms) setErrors(prev => ({ ...prev, terms: undefined }))
                }}
                className="mt-0.5"
              />
              <Label htmlFor="terms" className="text-sm font-normal leading-snug cursor-pointer">
                <Link href="/terms" className="text-primary hover:underline">Foydalanish shartlari</Link>
                {' '}va{' '}
                <Link href="/privacy" className="text-primary hover:underline">Maxfiylik siyosati</Link>
                ga roziman
              </Label>
            </div>
            {errors.terms && (
              <p className="text-xs text-destructive">{errors.terms}</p>
            )}
          </div>

          {/* Submit Button */}
          <Button
            type="submit"
            className="w-full bg-primary hover:bg-primary-dark text-primary-foreground"
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Ro&apos;yxatdan o&apos;tilmoqda...
              </>
            ) : (
              'Ro\'yxatdan o\'tish'
            )}
          </Button>
        </form>

        {/* Divider */}
        <div className="relative my-6">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t border-border" />
          </div>
          <div className="relative flex justify-center text-xs uppercase">
            <span className="bg-card px-2 text-muted-foreground">yoki</span>
          </div>
        </div>

        {/* Social Login */}
        <div className="grid grid-cols-2 gap-3">
          <Button variant="outline" className="w-full">
            <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24">
              <path
                fill="currentColor"
                d="M12.545,10.239v3.821h5.445c-0.712,2.315-2.647,3.972-5.445,3.972c-3.332,0-6.033-2.701-6.033-6.032s2.701-6.032,6.033-6.032c1.498,0,2.866,0.549,3.921,1.453l2.814-2.814C17.503,2.988,15.139,2,12.545,2C7.021,2,2.543,6.477,2.543,12s4.478,10,10.002,10c8.396,0,10.249-7.85,9.426-11.748L12.545,10.239z"
              />
            </svg>
            Google
          </Button>
          <Button variant="outline" className="w-full">
            <svg className="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2C6.477 2 2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.879V14.89h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.989C18.343 21.129 22 16.99 22 12c0-5.523-4.477-10-10-10z" />
            </svg>
            Facebook
          </Button>
        </div>

        {/* Login Link */}
        <p className="text-center text-sm text-muted-foreground mt-6">
          Hisobingiz bormi?{' '}
          <Link href="/auth/login" className="text-primary font-medium hover:underline">
            Kirish
          </Link>
        </p>
      </div>
    </div>
  )
}
